### ISSUE TITLE
Does this a public edit project?

### ISSUE THREAD

**Issue by xxAna** [ZhiyuanChen/papers#1]
It seems a well organized project. Does it a public edit project or just for personal record? Can I also upload my collections on it?

**Comment by ZhiyuanChen** [comment]
> It seems a well organized project. Does it a public edit project or just for personal record? Can I also upload my collections on it?

Of course it's a public edit project, it's a public repo!
Any pull request is welcome!

**Comment by xxAna** [comment]
OK. I get it. Thank you for your reply.^-^
